baseURL = "https://example.org"

disableKinds = ["section", "taxonomy", "term"]

enableInlineShortcodes = true


[module]
  [module.hugoVersion]
    extended = false
    min = "0.75.0"

[build]
# Used by PurgeCSS
writeStats = true